version: 2
formats: all
python:
    version: 3
    install:
        - requirements: docs/requirements.txt
        - method: pip
          path: .
          extra_requirements: [test]
sphinx:
    configuration: docs/source/conf.py
    fail_on_warning: true
